version: '3'
services:
  jenkins-lts:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - "/Users/mac/PycharmProjects/pytestFramework/Jenkins/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"